create extension if not exists pgcrypto;

create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  price numeric not null,
  cost_price numeric not null,
  stock_level integer not null,
  low_stock_threshold integer not null,
  last_sold_date timestamptz null,
  created_at timestamptz not null default now()
);

create table if not exists public.sales (
  id uuid primary key default gen_random_uuid(),
  receipt_number bigint generated by default as identity,
  items jsonb not null,
  total numeric not null,
  profit numeric not null,
  date timestamptz not null,
  created_at timestamptz not null default now()
);

create or replace function public.process_sale(cart jsonb)
returns public.sales
language plpgsql
as $$
declare
  v_total numeric := 0;
  v_profit numeric := 0;
  v_now timestamptz := now();
  line jsonb;
  item_id uuid;
  qty integer;
  price numeric;
  v_item public.inventory_items;
  v_sale public.sales;
begin
  if cart is null or jsonb_typeof(cart) <> 'array' then
    raise exception 'Invalid cart';
  end if;

  for line in select * from jsonb_array_elements(cart) loop
    item_id := (line->>'itemId')::uuid;
    qty := (line->>'quantity')::integer;
    price := (line->>'price')::numeric;

    if qty is null or qty <= 0 then
      raise exception 'Quantity must be positive';
    end if;

    select * into v_item
    from public.inventory_items
    where id = item_id
    for update;

    if not found then
      raise exception 'Item not found: %', item_id;
    end if;

    if v_item.stock_level < qty then
      raise exception 'Not enough stock for %', v_item.name;
    end if;

    v_total := v_total + price * qty;
    v_profit := v_profit + (price - v_item.cost_price) * qty;
  end loop;

  for line in select * from jsonb_array_elements(cart) loop
    item_id := (line->>'itemId')::uuid;
    qty := (line->>'quantity')::integer;

    update public.inventory_items
    set stock_level = stock_level - qty,
        last_sold_date = v_now
    where id = item_id;
  end loop;

  insert into public.sales (items, total, profit, date)
  values (cart, v_total, v_profit, v_now)
  returning * into v_sale;

  return v_sale;
end;
$$;
